# Generated by Django 2.0.3 on 2018-11-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_api', '0003_auto_20181113_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.CharField(max_length=500),
        ),
    ]
